version: "3.9"
services:
  qin_ser_java:
    tty: true
    stdin_open: true
    container_name: qin_con_java
    build: .
    volumes:
      - ${QIN_ROOT}/Work:/root
      - ${QIN_ROOT}/Arch:/root/Arch
      - ${QIN_ROOT}/Code:/root/Code
      - ${QIN_ROOT}/Pool:/root/Pool
      - ${QIN_ROOT}/Prod:/root/Prod
      - ${QIN_ROOT}/Test:/root/Test
    networks:
      - qin_net_stk_java
    
networks:
  qin_net_stk_java:
    external: true