version: "3.9"
services:
  qcode_ser_qin_vessels:
    tty: true
    stdin_open: true
    container_name: qcode_con_qin_vessels
    image: pointeldevs/stk_base
    volumes:
      - ${QIN_ROOT}/Work:/root
      - ${QIN_ROOT}/Arch:/root/Arch
      - ${QIN_ROOT}/Code:/root/Code
      - ${QIN_ROOT}/Pool:/root/Pool
      - ${QIN_ROOT}/Prod:/root/Prod
      - ${QIN_ROOT}/Test:/root/Test
    environment:
      - QIN_ROOT=/root
    networks:
      - qin_net_stk
    working_dir: /root/Code/qin_vessels

networks:
  qin_net_stk:
    external: true