version: "3.9"
services:
  qvess_ser_run_java:
    tty: true
    stdin_open: true
    container_name: qvess_run_java
    image: pointeldevs/run_java
    build: .
    volumes:
      - ${QIN_ROOT}/Work:/root
      - ${QIN_ROOT}/Arch:/root/Arch
      - ${QIN_ROOT}/Code:/root/Code
      - ${QIN_ROOT}/Pool:/root/Pool
      - ${QIN_ROOT}/Prod:/root/Prod
      - ${QIN_ROOT}/Test:/root/Test
    environment:
      - QIN_ROOT=/root
    networks:
      - qin_net_run

networks:
  qin_net_run:
    external: true