version: "3.9"
services:
  qser_run_pgadmin:
    container_name: qcon_run_pgadmin
    image: dpage/pgadmin4
    volumes:
      - ${QIN_ROOT}/Arch:/Pointel/Arch
    environment:
      - QIN_ROOT=/Pointel
      - PGADMIN_DEFAULT_EMAIL=pgadmin@pointel.com.br
      - PGADMIN_DEFAULT_PASSWORD=pgadmin
    ports:
      - "15433:80"
    networks:
      - qin_net_run

networks:
  qin_net_run:
    external: true
